#!/usr/bin/env python3

import os
import http.server

address = ("192.168.254.51", 8889)
handler = http.server.SimpleHTTPRequestHandler
os.chdir("status")
cwd = os.getcwd()

httpd = http.server.HTTPServer(address, handler)
print("serving {} at port {}".format(cwd, address[1]))
httpd.serve_forever()

